
package GUI;

import Node.*;
import personajes.*;
import EstructuraDeDatos.*;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {
    private int unidadesDesplegadas = 0;
    ListaCircular listaC = new ListaCircular();
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContinuarB = new javax.swing.JButton();
        ArqueroB = new javax.swing.JButton();
        MagoB = new javax.swing.JButton();
        CaballeroB = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ContinuarB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Captura de pantalla 2023-04-21 024047.png"))); // NOI18N
        ContinuarB.setBorderPainted(false);
        ContinuarB.setContentAreaFilled(false);
        ContinuarB.setDefaultCapable(false);
        ContinuarB.setFocusPainted(false);
        ContinuarB.setFocusable(false);
        getContentPane().add(ContinuarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 90, 20));

        ArqueroB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Arquero.png"))); // NOI18N
        ArqueroB.setText("jButton2");
        ArqueroB.setBorderPainted(false);
        ArqueroB.setContentAreaFilled(false);
        ArqueroB.setDefaultCapable(false);
        ArqueroB.setFocusPainted(false);
        ArqueroB.setRequestFocusEnabled(false);
        ArqueroB.setVerifyInputWhenFocusTarget(false);
        ArqueroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArqueroBActionPerformed(evt);
            }
        });
        getContentPane().add(ArqueroB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 150, 200));

        MagoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Mago.png"))); // NOI18N
        MagoB.setText("jButton3");
        MagoB.setBorderPainted(false);
        MagoB.setContentAreaFilled(false);
        MagoB.setDefaultCapable(false);
        MagoB.setFocusPainted(false);
        MagoB.setFocusable(false);
        MagoB.setRequestFocusEnabled(false);
        MagoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MagoBActionPerformed(evt);
            }
        });
        getContentPane().add(MagoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 120, 170));

        CaballeroB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/Caballero.png"))); // NOI18N
        CaballeroB.setText("jButton1");
        CaballeroB.setBorderPainted(false);
        CaballeroB.setContentAreaFilled(false);
        CaballeroB.setDefaultCapable(false);
        CaballeroB.setFocusPainted(false);
        CaballeroB.setFocusable(false);
        CaballeroB.setRequestFocusEnabled(false);
        CaballeroB.setVerifyInputWhenFocusTarget(false);
        CaballeroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaballeroBActionPerformed(evt);
            }
        });
        getContentPane().add(CaballeroB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 140, 160));

        jLabel2.setBackground(new java.awt.Color(102, 102, 0));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("SELECCIONE LOS PERSONAJES PARA ESTA RONDA");
        jLabel2.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel2.setDoubleBuffered(true);
        jLabel2.setFocusCycleRoot(true);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 410, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/91WLVxaIU8L.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 1210, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 870, 500));

        setSize(new java.awt.Dimension(1041, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ArqueroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArqueroBActionPerformed
        String cantidad = JOptionPane.showInputDialog("Ingrese la cantidad de unidades que desea desplegar de este campeon");
        int cantidadN = Integer.parseInt(cantidad);
        if (unidadesDesplegadas + cantidadN > 4) {
            JOptionPane.showMessageDialog(null, "No se pueden desplegar mas de 4 Unidades");
        }else{
            unidadesDesplegadas += cantidadN;
            for (int i = 0; i< cantidadN; i++){
                listaC.agregar(new Personaje("Arquero",1.0,"Roca"));
            }
        }
        listaC.imprimir();        
    }//GEN-LAST:event_ArqueroBActionPerformed

    private void CaballeroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaballeroBActionPerformed
        String cantidad = JOptionPane.showInputDialog("Ingrese la cantidad de unidades que desea desplegar de este campeon");
        int cantidadN = Integer.parseInt(cantidad);
        if (unidadesDesplegadas + cantidadN >4){
            JOptionPane.showMessageDialog(null, "No se pueden desplegar mas de 4 Unidades");
        }else{
            unidadesDesplegadas += cantidadN;
            for (int i = 0; i< cantidadN; i++){
                listaC.agregar(new Personaje("Caballero",2.0,"Papel"));
            }    
        }
        listaC.imprimir();
    }//GEN-LAST:event_CaballeroBActionPerformed

    private void MagoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MagoBActionPerformed
       String cantidad = JOptionPane.showInputDialog("Ingrese la cantidad de unidades que desea desplegar de este campeon");
        int cantidadN = Integer.parseInt(cantidad);
        if (unidadesDesplegadas + cantidadN >4){
            JOptionPane.showMessageDialog(null, "No se pueden desplegar mas de 4 Unidades");
        }else{
            unidadesDesplegadas += cantidadN; 
            for (int i = 0; i< cantidadN; i++){
                listaC.agregar(new Personaje("Mago",1.5,"Tijera"));
            }   
        }
        listaC.imprimir();
    }//GEN-LAST:event_MagoBActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArqueroB;
    private javax.swing.JButton CaballeroB;
    private javax.swing.JButton ContinuarB;
    private javax.swing.JButton MagoB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
